import { useState , useEffect } from 'react'

import axios from 'axios'

import Head from 'next/head'
import styles from '../styles/Home.module.css'
import stylesTrust from '../styles/Trust.module.css'

import fs from 'fs'
import {X509Certificate} from 'crypto'
import path from 'path'
import Pagination from '../components/paginationTrust'
import { paginate } from './paginate'

const Tablemodels = ({data}) => {
    
    const [posts, setPosts] = useState([])
    useEffect(() =>{
        const getPosts = async () =>{
            //const {data: res} = await axios.get('https://jsonplaceholder.typicode.com/posts')
            setPosts(data)
        }
        getPosts()
    },[])

    //console.log(posts.length)

    const [currentPage,  setCurrentPage] = useState(1);
    const pageSize = 10
    const handlePageChange = (page) => {
        setCurrentPage(page)
    }
    console.log(useState(1))
    console.log(currentPage)
    
    const PaginatePosts = paginate(posts, currentPage, pageSize)

    return (
        <div className={styles.container} >
            <Head>
                <title>Trust Store Mozilla</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}> 
                <table className='table'>
                    <thead>
                        <tr>
                            <th className={stylesTrust.col_1}>ID</th>
                            <th className={stylesTrust.col_1}>Nro de Serial</th>
                            <th className={stylesTrust.col_1}>Nombre</th>
                            <th className={stylesTrust.col_1}>Validez<p className={stylesTrust._p}>Desde-Hasta</p></th>
                            <th className={stylesTrust.col_1}>Llave pública<p className={stylesTrust._p}>Algoritmo-Tamaño</p></th>
                            <th className={stylesTrust.col_1}>SHA-1</th>
                        </tr>
                    </thead>
                    <tbody>
                        {
                            PaginatePosts.map((post) => 
                            (
                                <tr key={post.id}>
                                    <td className={stylesTrust.col_2}>{post.id}</td>
                                    <td className={stylesTrust.col_2}>{post.nmSerial}</td>
                                    <td className={stylesTrust.col_2}>{post.subject}</td>
                                    <td className={stylesTrust.col_2}>{post.validFrom} - {post.validTo}</td>
                                    <td className={stylesTrust.col_2}>RSA - {post.nmBits}</td>
                                    <td className={stylesTrust.col_2}>{post.certSha}</td>                            
                                </tr>        
                            ))
                        }
                        
                    </tbody>
                </table>
                <Pagination items = {posts.length} pageSize = {pageSize} currentPage = {currentPage}  onPageChange = {handlePageChange}/>
            </main>
        

            <footer className={styles.footer}>
            Grupo@4 Unidos
            </footer>

        </div>
    );
};


export const getStaticProps = async () => {
    const postsDirectory = path.join(process.cwd(),'public', 'trustStore','MozillaRootsPEM.txt')
    // const filenames = await fs.readFileSync(postsDirectory)
    let filenames = await fs.readFileSync(postsDirectory)
    let certificateCiphered = []

    filenames.toString().split(/\n-----END CERTIFICATE-----/).forEach(function(certificate){
    // do something here with each line
        const certificateCipher = certificate + "\n-----END CERTIFICATE-----"
        if(certificateCipher != "\n-----END CERTIFICATE-----")
            certificateCiphered.push(certificateCipher);
    });
    
    let x509list = ""
    let result = ""
    // let certificateDeciphered = []
    
    let id = 0

    const data = certificateCiphered.map(async (cert) => {
        // console.log(cert)
        x509list = new X509Certificate(cert);
        result = x509list.toLegacyObject()
        //console.log(result)
        const listNameCert = result.subject
        //console.log(ggg)
        //console.log((ggg.split(/\n/)))
        let nameCert = ""
        listNameCert.split(/\n/).forEach(function(listname){
            const inToremove = "O="
            if (listname.includes(inToremove)) {
                nameCert = listname.replaceAll(inToremove, "");
            }
        });

        //console.log(nameCert)
        id++
        return {
            id: id,
            subject: nameCert,
            nmSerial: result.serialNumber,
            validFrom: result.valid_from,
            validTo: result.valid_to,
            certSha: result.fingerprint,
            nmBits: result.bits,
            pubKey: toString(result.pubkey),
        }
        //certificateDeciphered.push(result)
    });
    return {
        props: {
            data: await Promise.all(data),
        },
    }

};


export default Tablemodels;