import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
//import Router, { useRouter } from 'next/router'

import styles from '../styles/Home.module.css'
import validate_url from './validate_url'
import validate_protocol from './validate_protocol'


export default function Home() {

  const handleClick = (e, path) => {
    e.preventDefault()
    if (path === "/verificar") {
      const nameURL = document.querySelector('#linkUrl').value
      const isLink = validate_url(nameURL);
      
      console.log(isLink);
      if (nameURL == ""){
        alert('Rellene el campo');
      }
      else if (isLink) {
        const showProtocol = validate_protocol(nameURL);
        if (showProtocol.protocol == 'https:') {
          console.log('lo lograste onichan');
          //console.log(read_pem());
          //Router.push('/listTrustStore')

        }else{
          alert('Protocolo inseguro: ', showProtocol.protocol );
        }
        //mostrar codigo o los certificados
      }else{
        alert('No es un link URL');
      }
      
    }
    // if (path === "/posts") {
    //   console.log("I clicked on the Posts Page");
    // }
  };
  
  return (
      <div className={styles.container}>
        <Head>
         <title>Verify your Certification Digital Free</title>
         <meta name="description" content="Generated by create next app" />
         <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h2 className={styles.title}>
            Digital Certicates Trust Verifer
          </h2>
          
          <div>
            <form className={styles.main_form}>
              <div className={styles.main_form_inputs}>
                {/* <input className={styles.input__url} type="url" name="url" placeholder="[ ingresar URL a verificar ]"/> */}
                <input className={styles.controls} type="url" name="linkUrl" id="linkUrl" placeholder="[ ingresar URL a verificar ]"></input>

                <div className={styles.main_button} id="main_button_veri">
                  <div id="circle"></div>
                  <Link href="">
                    <a onClick={(e) => handleClick(e, "/verificar")}>Verificar</a>
                  </Link>
                  {/* <a href="#">Verificar</a> */}
                </div>

                <div className={styles.main_button} id="main_button_veri">
                  <div id="circle"></div>
                  <Link href="/">
                    <a onClick={(e) => handleClick(e, "/Archivos")}>Archivos</a>
                  </Link>
                  {/* <input className={styles.input__file} type="file" name="archivos"/>  */}
                  {/* <button type="submit">Submit</button> */}
                </div>

                {/* <input className={styles.input__button} type="button" name="verificar" value="Verificar"/> */}

                {/* <input className={styles.input__file} type="file" name="archivos"/>  */}
              </div>
              
            </form>
          </div>

    
          <div className={styles.card}>
            <div className={styles.card_url}>
              <p >www.unsa.edu.pe</p>
            </div>
            <div className={styles.search__results__browsers}>
              <p>Microsft Egde</p>
              <div>
                <span className={styles.search__results__browsers__dot}></span>
                <span className={styles.search__results__browsers__dot}></span>
                <span className={styles.search__results__browsers__dot}></span>
              </div>
             
            </div>
            <div className={styles.search__results__browsers}>
              <p>Google Chrome</p>
              <div>
                <span className={styles.search__results__browsers__dot}></span>
                <span className={styles.search__results__browsers__dot}></span>
                <span className={styles.search__results__browsers__dot}></span>
              </div>
            </div>
            <div className={styles.search__results__browsers}>
              <p>Mozila Firefox</p>
              <div>
                <span className={styles.search__results__browsers__dot}></span>
                <span className={styles.search__results__browsers__dot}></span>
                <span className={styles.search__results__browsers__dot}></span>
              </div>
              
            </div>

          </div>

          <div className={styles.main_button} id="main_button_veri">
            <div id="circle"></div>
            {/* <input className={styles.input__file} type="file" name="archivos"/>  */}
            <a href="#">Limpiar Todo</a>
          </div>
          {/* <div className={styles.button_clear}>
            <button type="button" class="button-clear__all">
              Limpiar todo
            </button>
          </div> */}

        </main>


        <footer className={styles.footer}>
          <Link href="/generateTable">
            <a className = {styles.text_link} >
              Ver Mozila Trust Store
              <span className={styles.logo}>
                <Image src="/firefox.svg" alt="Vercel Logo" width={30} height={20} />
              </span>
              </a>
          </Link>

          <Link href="/">
            <a className = {styles.text_link} >
              Ver Microsft Trust Store
              <span className={styles.logo}>
                <Image src="/firefox.svg" alt="Vercel Logo" width={30} height={20} />
              </span>
              </a>
          </Link>
          
          <Link href="/">
            <a className = {styles.text_link} >
              Ver Google Truste Store
              <span className={styles.logo}>
                <Image src="/firefox.svg" alt="Vercel Logo" width={30} height={20} />
              </span>
              </a>
          </Link>

        </footer>

        </div>
  )
}
